import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navigation from "./nav";
import Header from "./header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="ja">
      <body>
        <header>
          <Header/>
        </header>
        <nav>
          <Navigation/>
        </nav>
          {children}
      </body>
    </html>
  );
}
