import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Image from "next/image"
import localImage from "../public/logo.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <nav>
          <ul>
            <li>
              <Image width={200} src={localImage} alt="ロゴ画像"/>
            </li>
            <li>
              ダッシュボード
            </li>
            <li>
              今日の記録
            </li>
            <li>
              今月の記録
            </li>
            <li>
              マスタ登録
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
